name: Probending
author: ProjectKorra
version: 1.0.0
main: com.projectkorra.probending.Probending
depend: []
softdepend: [Vault, WorldGuard]
commands:
  probending:
    aliases: [pb]
permissions:
  probending.admin:
    default: op
    children:
      probending.command.team.disband.other: true
      probending.command.reload: true
      probending.command.team.addwin: true
      probending.command.team.addloss: true
      probending.command.round.start: true
      probending.command.round.stop: true
      probending.worldguard.buildonfield: true
      probending.command.setspawn: true
      probending.command.arena.create: true
      probending.command.arena.delete: true
      probending.command.arena.setspawn: true
      probending.command.arena.setworld: true
      probending.command.arena.setzone: true
      probending.user: true
  probending.user:
    default: true
    children:
      probending.command.team.create: true
      probending.command.team.invite: true
      probending.command.team.info: true
      probending.command.team.join: true
      probending.command.team.kick: true
      probending.command.team.quit: true
      probending.command.team.list: true
      probending.command.team.rename: true
      probending.command.team.disband: true
      probending.command.chat: true
      probending.command.arena.list: true